project_id = "zfbgxnllkhbrligqdcek"

[functions.create-client-user]
verify_jwt = false

[functions.sync-tracksolid]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.reset-client-user-password]
verify_jwt = false
